{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeless.fullname" . }}-ui
  labels:
    app.kubernetes.io/name: {{ include "kubeless.name" . }}
    helm.sh/chart: {{ include "kubeless.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    kubeless: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kubeless.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    kubernetes: ui
{{- end }}
